# Site settings
title: Chaosmail Blog
email: office(at)chaosmail.at
description: "MSc Student in Computer Science at Vienna University of Technology"
baseurl: ""
url: "http://chaosmail.github.io/"
twitter_username: ChrisiKrnr
github_username:  chaosmail
paginate: 10

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge

kramdown:
 input: GFM

gems:
  - jekyll-paginate